vulkan_driver=1
legacy_layout=0
engine_version=0
show_fps_limit=0
wine=0
gamemode=0

fps=1
fps_only=0
frametime=0
frame_timing=0
dynamic_frame_timing=0
histogram=0

vsync=1
fps_limit=120
fps_limit_method=early

gpu_list=0
gpu_stats=1
gpu_core_clock=1
gpu_fan=1
gpu_temp=1
gpu_junction_temp=1
gpu_power=1
gpu_power_limit=0
vram=0
gpu_mem_clock=1
gpu_mem_temp=1

throttling_status=0

cpu_stats=0
cpu_temp=1
cpu_mhz=1
cpu_power=0
cpu_load_change=0
core_load=0

ram=0

position=bottom-right
offset_x=0
offset_y=0

font_size=24

alpha=0.95
background_alpha=0
gpu_color=EFEFEF
engine_color=EFEFEF
text_color=EFEFEF
text_outline=2
text_outline_color=222222
text_outline_thickness=1
frametime_color=EFEFEF

log_duration=180
log_interval=0
output_folder=/home/fyr/tmp/mangohud

# hotkey
toggle_hud=End
toggle_fps_limit=F12
toggle_logging=F13