title   Arch
linux   /vmlinuz-linux
initrd  /amd-ucode.img
initrd  /initramfs-linux.img
options root=UUID=3c92c168-c1f4-4bd7-959a-61cea573d7b6 rw quiet loglevel=3 rd.systemd.show_status=auto rd.udev.log_level=3 nvidia_drm.modeset=1 nvidia_drm.fbdev=1 NVreg_EnableResizableBar=1
