title   Arch
linux   /vmlinuz-linux-zen
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options root=UUID=3c92c168-c1f4-4bd7-959a-61cea573d7b6 rw quiet loglevel=3 rd.systemd.show_status=auto rd.udev.log_level=3 amd_pstate=active amdgpu.ppfeaturemask=0xffffffff
