[main]
namespace=launcher

prompt=" "
terminal=foot
font=cozette:size=11
use-bold=no
dpi-aware=no

icons-enabled=yes
icon-theme=hicolor
image-size-ratio=0

fields=filename,name,generic,exec
match-mode=fzf
sort-result=yes

show-actions=no
list-executables-in-path=no

lines=40
minimal-lines=yes
width=50
horizontal-pad=30
vertical-pad=4
inner-pad=4

layer=overlay
anchor=top-left
x-margin=15
y-margin=15

keyboard-focus=on-demand
exit-on-keyboard-focus-loss = yes
scaling-filter=cubic

[colors]
background=121212ff
text=D9EAE2ff
match=CA3448ff
selection-match=CA3448ff
selection=9FB9A8aa
selection-text=D9EAE2ff
border=D9EAE2ff

[border]
width=2
radius=4

[dmenu]
mode=text
# exit-immediately-if-empty=no
