prompt="> "  
terminal=foot -e
font=cozette:size=8
use-bold=no
line-height=<use font metrics>
dpi-aware=no

icons-enabled=yes
icon-theme=hicolor
image-size-ratio=0

fields=filename,name,generic,exec
fuzzy=fzf
sort-result=yes

show-actions=no
list-executables-in-path=no

lines=20
width=40
horizontal-pad=30
vertical-pad=8
inner-pad=8

layer=top
anchor=centre
x-margin=500
y-margin=0

exit-on-keyboard-focus-loss = no

[colors]
background=121212ff
text=D9EAE2ff
match=CA3448ff
selection-match=CA3448ff
selection=9FB9A8aa
selection-text=D9EAE2ff
border=D9EAE2ff

[border]
width=2
radius=12

[dmenu]
mode=text
# exit-immediately-if-empty=no
