# critical
unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g mode-keys vi
set -g status-keys vi
set -g detach-on-destroy on

# default unbinds
unbind l
unbind s
unbind %
unbind '"'

# session/window binds
bind b new
bind X kill-session
bind r source-file ~/.tmux.conf

# pane binds
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind s split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind -r H resize-pane -L 20
bind -r J resize-pane -D 20
bind -r K resize-pane -U 20
bind -r L resize-pane -R 20

# layout binds
bind N next-layout
bind P previous-layout

# copy binds
bind e copy-mode
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'C-v' send-keys -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel

# help
bind-key E show-environment -g
bind-key ? display-popup -E 'tmux list-keys | cut -c 29- | fzf --reverse --ansi | xargs -I % tmux display-message "%"'

# status
set -g status on
set -g status-style bg=default
set -g visual-activity off
set -g monitor-activity on
set -g status-left ""
set -g status-position bottom
set -g status-right "#[bg=default,fg=white] #(hostnamectl hostname) 𜰟 #(date '+%H%M') hrs "
set -g status-right-length 80
set -g window-status-bell-style bg=red,fg=white
set -g window-status-format "#[bg=black,fg=white] #I #W "
set -g window-status-current-format "#[bg=white,fg=black] #I #W "
set -g status-justify left
set -g status-interval 1
set -g display-time 4000
set -g popup-border-lines padded

# pane
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g pane-border-lines heavy
set -g pane-border-status bottom
set -g pane-border-format ''
set -g pane-scrollbars modal

# title
set -g allow-rename on
set -g set-titles off
set -g set-titles-string "tmux: #T"
set -g automatic-rename off

# mode colours
set -g mode-style bg=white,fg=black
set -g pane-border-style fg=black
set -g pane-active-border-style fg=white
set -g clock-mode-colour white
set -g message-style bg=white,fg=black
set -g message-command-style bg=white,fg=black
set -g popup-style bg=white,fg=black
set -g popup-border-style bg=white,fg=black
set -g display-panes-active-colour white
set -g display-panes-colour black
set -g menu-style fg=white,bg=default
set -g menu-selected-style fg=black,bg=white
set -g pane-scrollbars-style fg=black,bg=white

# cursor
set -g cursor-colour white
set -g cursor-style underline

# copy mode colours
set -g copy-mode-selection-style bg=white,fg=black
set -g copy-mode-match-style bg=white,fg=black
set -g copy-mode-mark-style bg=cyan,fg=white
set -g copy-mode-current-match-style bg=red,fg=white
set -g copy-mode-position-format ''

# misc. settings
set -g mouse on
set -g escape-time 0   # Vim Insta Escape
set -g repeat-time 500 # Key Repeats
set -g history-limit 10000
set -g default-command /bin/zsh