servers:
  - name: blaze.lan
    url: 'http://blaze.lan:8096'
    username: 'fyr'
    password_file: /home/fyr/.jellyfin-tui-pw
    default: true

art: true
persist: true
auto_color: true
lyrics: never

rounded_corners: true

window_title: true

mpv:
  replaygain: album
  af: lavfi=[loudnorm=I=-16:TP=-3:LRA=4]
  no-config: true

# themes:
#   - name: "Transparent Dark"
#     background: "none"
