#!/bin/sh

DISPLAY=:1

xrandr --output DisplayPort-0 --primary --mode 2560x1440 -r 239.97 \
       --output DisplayPort-1 --off \
       --output HDMI-0 --off \
       --output HDMI-1 --off &> /dev/null

wmp -a 1280 720
xset s off -dpms
xsetroot -cursor_name left_ptr

[ -f ~/.Xresources ] && xrdb -load -I$HOME ~/.Xresources

hsetroot -cover "/home/fyr/usr/backs/black_waves.jpg"
xclock -d -face "lemon-8" -padding 8 -update 5 2> /dev/null &
sxhkd &

xset r rate 180 50

# event handler
wew | while read -r ev wid; do
    case $ev in
        CREATE)
            case $(atomx WM_CLASS $wid) in
                steam_app_*)
                    wtf $wid
                    chwso -r $wid
                    wtp $(wattr xywh $(lsw -r)) $wid
                    atomx GROUP=3 $wid
                    chwb -s 0 $wid
                    ;;
                xclock)
                    ignw -s $wid
                    chwb -s 2 -c 0xEEEEEE $wid
                    atomx GROUP=8 $wid
                    wmv 12 12 $wid
                    ;;
                *)
                    wattr o $wid || {
                        chwb -s 2 -c 0x1C1C1C $wid
                        wtf $wid
                        wmv -a $(wmp) $wid
                        chwso -r $wid
                        chwb -s 2 -c 0xEEEEEE $wid
                    }
                    ;;
            esac
            ;;
        ENTER)
            wattr o $wid || {
                chwb -s 0 $(pfw)
                wtf $wid
                chwb -s 2 -c 0xEEEEEE $wid
            }
            ;;
        DESTROY)
            ;;
    esac
done
